-- =============================================================================
-- ArogyaLink – SQLite Schema (Offline Mobile Database)
-- For: Person 1 – ASHA/ANM Mobile Application
-- =============================================================================
-- This SQLite database lives on the ASHA worker's mobile device.
-- It stores patient data OFFLINE so the ASHA worker can keep working
-- even without internet connectivity.
--
-- When internet returns, a sync API uploads records to the central
-- PostgreSQL database (managed by Person 3 backend).
--
-- KEY DESIGN DECISIONS:
--   - Every table has a `local_id` (SQLite auto-increment PK) as the
--     primary key for local operations.
--   - `server_id` stores the CUID assigned by PostgreSQL after sync.
--     It is NULL until the record has been successfully synced.
--   - `sync_status` drives the sync engine:
--       'PENDING' → not sent yet
--       'SYNCED'  → confirmed by server
--       'FAILED'  → sync attempted but server rejected/errored
--   - `device_id` identifies WHICH device created the record.
--     This prevents duplicates when multiple devices sync the same patient.
--   - `last_synced_at` is the timestamp of the last successful sync.
--
-- Sync Flow:
--   1. ASHA creates patient offline → sync_status = 'PENDING'
--   2. Internet becomes available
--   3. Sync engine reads all rows WHERE sync_status = 'PENDING'
--   4. Uploads to server → server returns server_id (CUID)
--   5. Update local row: server_id = <cuid>, sync_status = 'SYNCED'
--   6. If server returns error → sync_status = 'FAILED', log in sync_log
-- =============================================================================

-- Enable foreign key enforcement in SQLite (off by default)
PRAGMA foreign_keys = ON;

-- =============================================================================
-- TABLE: patients
-- =============================================================================
-- The primary record for every patient registered by the ASHA worker.
-- This is the root table – encounters, vitals, etc. link back to this.
CREATE TABLE IF NOT EXISTS patients (
    -- Local auto-increment ID used for all local FK references
    local_id        INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Set by the server after sync; NULL if not yet synced
    server_id       TEXT UNIQUE,

    -- --- Patient Identity ---
    name            TEXT NOT NULL,              -- Patient's full name
    date_of_birth   TEXT NOT NULL,              -- ISO 8601 date: "YYYY-MM-DD"
    gender          TEXT NOT NULL CHECK(gender IN ('MALE', 'FEMALE', 'OTHER')),
    phone           TEXT,                       -- Patient's or guardian's phone (optional)
    address         TEXT,                       -- Full address (optional)
    village         TEXT NOT NULL,              -- Village name (important for rural targeting)
    district        TEXT NOT NULL,              -- District
    state           TEXT NOT NULL,              -- State

    -- The ASHA worker who registered this patient (server-side user ID)
    assigned_asha_id TEXT NOT NULL,

    -- UUID generated by the mobile app before sync to prevent duplicates
    -- If the same record is uploaded twice, server checks this to deduplicate
    sync_id         TEXT UNIQUE,

    -- --- Sync Tracking Columns (same purpose for all tables) ---
    sync_status     TEXT NOT NULL DEFAULT 'PENDING' CHECK(sync_status IN ('PENDING', 'SYNCED', 'FAILED')),
    last_synced_at  TEXT,                       -- ISO 8601 datetime of last successful sync
    device_id       TEXT NOT NULL,              -- ID of the mobile device that created this record

    -- --- Timestamps ---
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Index to quickly find patients that still need to be synced
CREATE INDEX IF NOT EXISTS idx_patients_sync_status ON patients(sync_status);
CREATE INDEX IF NOT EXISTS idx_patients_assigned_asha ON patients(assigned_asha_id);


-- =============================================================================
-- TABLE: encounters
-- =============================================================================
-- Records a clinical interaction (PHC visit, teleconsult, etc.) for a patient.
-- Linked to a patient using the LOCAL patient_local_id (not server_id) so that
-- the relationship works even before the patient is synced to the server.
CREATE TABLE IF NOT EXISTS encounters (
    local_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id       TEXT UNIQUE,                -- Assigned by server after sync

    -- FK to local patients table (use local_id for offline relationships)
    patient_local_id INTEGER NOT NULL REFERENCES patients(local_id) ON DELETE CASCADE,

    -- The server-side doctor ID (entered manually or pre-loaded on the device)
    doctor_id       TEXT NOT NULL,

    -- The facility where this encounter happened
    facility_id     TEXT NOT NULL,

    -- Type of encounter (matches EncounterType enum in PostgreSQL)
    encounter_type  TEXT NOT NULL CHECK(encounter_type IN (
                        'PHC_VISIT', 'TELECONSULTATION', 'EMERGENCY', 'FOLLOW_UP_VISIT'
                    )),

    -- Comma-separated or JSON array of symptoms reported by patient
    -- SQLite doesn't have arrays, so store as JSON string: '["fever","cough"]'
    symptoms        TEXT NOT NULL DEFAULT '[]',

    -- Doctor's free-text clinical notes / findings
    clinical_notes  TEXT,

    -- When the encounter happened (ISO 8601 datetime)
    encounter_date  TEXT NOT NULL,

    -- --- Sync Tracking Columns ---
    sync_status     TEXT NOT NULL DEFAULT 'PENDING' CHECK(sync_status IN ('PENDING', 'SYNCED', 'FAILED')),
    last_synced_at  TEXT,
    device_id       TEXT NOT NULL,

    -- --- Timestamps ---
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_encounters_patient ON encounters(patient_local_id);
CREATE INDEX IF NOT EXISTS idx_encounters_sync_status ON encounters(sync_status);


-- =============================================================================
-- TABLE: vitals
-- =============================================================================
-- Clinical measurements taken by the ASHA/ANM worker.
-- Can be standalone (no encounter) or linked to an encounter.
CREATE TABLE IF NOT EXISTS vitals (
    local_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id           TEXT UNIQUE,

    -- FK to local patient (required)
    patient_local_id    INTEGER NOT NULL REFERENCES patients(local_id) ON DELETE CASCADE,

    -- FK to local encounter (optional – vitals can be recorded without a formal encounter)
    encounter_local_id  INTEGER REFERENCES encounters(local_id) ON DELETE SET NULL,

    -- --- Measurement Fields ---
    temperature         REAL,   -- Body temperature in °C (e.g., 37.5)
    heart_rate          INTEGER, -- Beats per minute (bpm)
    bp_systolic         INTEGER, -- Blood pressure systolic in mmHg (e.g., 120)
    bp_diastolic        INTEGER, -- Blood pressure diastolic in mmHg (e.g., 80)
    oxygen_saturation   REAL,   -- SpO2 percentage (e.g., 98.5)
    weight              REAL,   -- Body weight in kg

    -- Who recorded the vitals (server-side user ID of the ASHA/ANM/Doctor)
    recorded_by_id      TEXT NOT NULL,

    -- --- Sync Tracking Columns ---
    sync_status         TEXT NOT NULL DEFAULT 'PENDING' CHECK(sync_status IN ('PENDING', 'SYNCED', 'FAILED')),
    last_synced_at      TEXT,
    device_id           TEXT NOT NULL,

    -- --- Timestamp ---
    recorded_at         TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_vitals_patient ON vitals(patient_local_id);
CREATE INDEX IF NOT EXISTS idx_vitals_encounter ON vitals(encounter_local_id);
CREATE INDEX IF NOT EXISTS idx_vitals_sync_status ON vitals(sync_status);


-- =============================================================================
-- TABLE: prescriptions
-- =============================================================================
-- A prescription issued during an encounter.
-- medicine_details is stored as a JSON string because SQLite has no JSON array type.
-- Example value: '[{"name":"Paracetamol","dosage":"500mg","frequency":"TDS","duration":"5 days"}]'
CREATE TABLE IF NOT EXISTS prescriptions (
    local_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id           TEXT UNIQUE,

    -- FK to local patient and encounter
    patient_local_id    INTEGER NOT NULL REFERENCES patients(local_id) ON DELETE CASCADE,
    encounter_local_id  INTEGER NOT NULL REFERENCES encounters(local_id) ON DELETE CASCADE,

    -- Server-side ID of the prescribing doctor
    doctor_id           TEXT NOT NULL,

    -- JSON array of medicine objects
    -- Format: [{ "name": "...", "dosage": "...", "frequency": "...", "duration": "..." }]
    medicine_details    TEXT NOT NULL DEFAULT '[]',

    -- Additional instructions for the patient (e.g., "Take after meals")
    instructions        TEXT,

    -- --- Sync Tracking Columns ---
    sync_status         TEXT NOT NULL DEFAULT 'PENDING' CHECK(sync_status IN ('PENDING', 'SYNCED', 'FAILED')),
    last_synced_at      TEXT,
    device_id           TEXT NOT NULL,

    -- --- Timestamp ---
    created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_prescriptions_patient ON prescriptions(patient_local_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_encounter ON prescriptions(encounter_local_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_sync_status ON prescriptions(sync_status);


-- =============================================================================
-- TABLE: followups
-- =============================================================================
-- A scheduled follow-up task assigned to an ASHA/ANM worker.
-- Created by a doctor after an encounter or referral.
-- The ASHA worker updates status and records the outcome after visiting the patient.
CREATE TABLE IF NOT EXISTS followups (
    local_id                INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id               TEXT UNIQUE,

    -- FK to local patient (required)
    patient_local_id        INTEGER NOT NULL REFERENCES patients(local_id) ON DELETE CASCADE,

    -- FK to encounter that triggered this follow-up (optional)
    related_encounter_local_id INTEGER REFERENCES encounters(local_id) ON DELETE SET NULL,

    -- Server-side referral ID (optional; stored as text since referrals
    -- are typically created on the server, not locally on the device)
    related_referral_server_id TEXT,

    -- Server-side user ID of the ASHA/ANM assigned to this follow-up
    assigned_to_id          TEXT NOT NULL,

    -- When the follow-up should happen (ISO 8601 date)
    due_date                TEXT NOT NULL,

    -- Current status of the follow-up task
    status                  TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN (
                                'PENDING', 'IN_PROGRESS', 'COMPLETED', 'MISSED', 'ESCALATED', 'CANCELLED'
                            )),

    -- What happened during the follow-up (filled by ASHA after visit)
    outcome                 TEXT,

    -- Additional notes from the ASHA worker
    notes                   TEXT,

    -- Timestamp when follow-up was marked complete
    completed_at            TEXT,

    -- --- Sync Tracking Columns ---
    sync_status             TEXT NOT NULL DEFAULT 'PENDING' CHECK(sync_status IN ('PENDING', 'SYNCED', 'FAILED')),
    last_synced_at          TEXT,
    device_id               TEXT NOT NULL,

    -- --- Timestamps ---
    created_at              TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at              TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_followups_patient ON followups(patient_local_id);
CREATE INDEX IF NOT EXISTS idx_followups_status ON followups(status);
CREATE INDEX IF NOT EXISTS idx_followups_sync_status ON followups(sync_status);
CREATE INDEX IF NOT EXISTS idx_followups_assigned_to ON followups(assigned_to_id);


-- =============================================================================
-- TABLE: sync_log
-- =============================================================================
-- An audit log for every sync operation attempted by the mobile app.
-- This is the "black box" for debugging sync failures.
--
-- How it works:
--   - Before uploading a record, the sync engine writes a row with status='PENDING'
--   - If upload succeeds → update to status='SUCCESS'
--   - If upload fails   → update to status='FAILED', store error_message
--   - The sync engine uses this table to retry FAILED records
--
-- This table does NOT sync to the server – it is purely for local debugging.
CREATE TABLE IF NOT EXISTS sync_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Which table the record belongs to (e.g., 'patients', 'encounters')
    table_name      TEXT NOT NULL,

    -- The local_id of the record being synced
    local_id        INTEGER NOT NULL,

    -- The server_id returned after a successful sync (NULL on failure)
    server_id       TEXT,

    -- What operation was performed on the record
    action          TEXT NOT NULL CHECK(action IN ('INSERT', 'UPDATE')),

    -- Result of this sync attempt
    status          TEXT NOT NULL CHECK(status IN ('PENDING', 'SUCCESS', 'FAILED')),

    -- Error message from server or network (NULL on success)
    error_message   TEXT,

    -- When this sync was attempted (ISO 8601 datetime)
    attempted_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Index to quickly find all failed syncs for retry
CREATE INDEX IF NOT EXISTS idx_sync_log_status ON sync_log(status);
-- Index to find all sync history for a specific table+local_id
CREATE INDEX IF NOT EXISTS idx_sync_log_table_local ON sync_log(table_name, local_id);
