-- =============================================================================
-- ArogyaLink – Offline mobile database: NOTE (this file is no longer a schema)
-- =============================================================================
-- The ASHA app is a NATIVE ANDROID app (Kotlin). Its offline database is defined
-- in the app itself, with Room (SQLite) entities and DAOs. Room is the source of
-- truth for the on-device schema, so there is nothing to keep in sync here.
--
-- The contract between the app and this backend is the "Sync Routes" section of
-- README.md (POST /api/sync/upload, GET /api/sync/download).
--
-- What that contract means for the Room entities:
--
--   * Primary keys are client-generated UUID v4 strings (patients, encounters,
--     vitals, followups). The same UUID is the row's id on the server.
--     There is NO local_id / server_id pair and no id-mapping step.
--     (Records created on the web have server-generated string ids; they are
--     stored in the same `id` column.)
--
--   * Every synced entity stores the server's `updatedAt` (from the download or
--     from an "ok" upload result) and sends it back as `baseUpdatedAt` when the
--     user edits that record. That is the optimistic-concurrency token; the phone
--     never compares its own clock to the server's.
--
--   * Keep a local sync flag per row (e.g. PENDING / SYNCED) and mark a row SYNCED
--     only when its per-record upload result is "ok".
--
--   * Store the last download's `serverTimestamp` and use it as the next
--     `lastSyncedAt`.
--
--   * Referrals and prescriptions are read-only on the phone (download only).
--
-- The old SQLite schema that used local_id / server_id / syncId was removed
-- because it described the previous, incompatible sync design.
-- =============================================================================
